### ISSUE TITLE
pipx plus copier does not work as described in readme

### ISSUE THREAD

**Issue by kratsg** [scientific-python/cookie#396]
See below:

```
Lord Stark:~$ pipx install copier
  installed package copier 9.1.1, installed using Python 3.8.6
  These apps are now globally available
    - copier
⚠️  Note: '/Users/kratsg/.local/bin' is not on your PATH environment variable. These apps will not be globally
    accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your
    PATH in your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
Lord Stark:~$ pipx inject copier copier-templates-extensions
  injected package copier-templates-extensions into venv copier
done! ✨ 🌟 ✨
Lord Stark:~$ pipx run copier copy gh:scientific-python/cookie itkdb-reports --trust
Traceback (most recent call last):
  File "/Users/kratsg/.local/pipx/.cache/b3c4e793c52a986/bin/copier", line 5, in <module>
    from copier.__main__ import copier_app_run
  File "/Users/kratsg/.local/pipx/.cache/b3c4e793c52a986/lib/python3.8/site-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
  File "/Users/kratsg/.local/pipx/.cache/b3c4e793c52a986/lib/python3.8/site-packages/copier/main.py", line 46, in <module>
    from .subproject import Subproject
  File "/Users/kratsg/.local/pipx/.cache/b3c4e793c52a986/lib/python3.8/site-packages/copier/subproject.py", line 15, in <module>
    from .template import Template
  File "/Users/kratsg/.local/pipx/.cache/b3c4e793c52a986/lib/python3.8/site-packages/copier/template.py", line 20, in <module>
    from yamlinclude import YamlIncludeConstructor
ModuleNotFoundError: No module named 'yamlinclude'
```

**Comment by henryiii** [comment]
You need `pipx inject copier 'pyyaml-include<2'` until a new release is out, see https://github.com/copier-org/copier/issues/1568.

**Comment by henryiii** [comment]
We've added this to the inject command in the readme and in CI. There should be a release in the nearish future that fixes this.
