### ISSUE TITLE
AttributeError: 'float' object has no attribute 'split'

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [scientific-python/cookie#404]
[Online checking](https://learn.scientific-python.org/development/guides/repo-review/?repo=sphinx-doc%2Fsphinx&branch=master) of [sphinx-doc/sphinx](https://github.com/sphinx-doc/sphinx) generates this error:
```python
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 310, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 9, in 
  File "/lib/python3.11/site-packages/repo_review/processor.py", line 214, in process
    result = apply_fixtures({"name": name, **fixtures}, tasks[name].check)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/repo_review/fixtures.py", line 106, in apply_fixtures
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/sp_repo_review/checks/pyproject.py", line 92, in check
    return "minversion" in options and int(options["minversion"].split(".")[0]) >= 6
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'split'
```
That's because of this:
```toml
[tool.pytest.ini_options]
minversion = 6.0
```
I'll fix it with `minversion = "6.0"`. Nevertheless, repo-review should print an error, not crash.

**Comment by henryiii** [comment]
Already fixed in https://github.com/scientific-python/cookie/pull/398, not released yet though.

**Comment by henryiii** [comment]
Now in a release!
