### ISSUE TITLE
pipx plus copier broken again as described in readme

### ISSUE THREAD

**Issue by kratsg** [scientific-python/cookie#433]
Follow up from #396. See below output

```
Lord Stark:~/radiativeDecays (main)$ pipx install copier
'copier' already seems to be installed. Not modifying existing installation in '/Users/kratsg/.local/pipx/venvs/copier'. Pass '--force' to force
installation.

Lord Stark:~/radiativeDecays (main)$ pipx inject copier copier-templates-extensions
  injected package copier-templates-extensions into venv copier
done! ✨ 🌟 ✨

Lord Stark:~/radiativeDecays (main)$ copier copy gh:scientific-python/cookie atlas --trust
Traceback (most recent call last):
  File "/Users/kratsg/.local/bin/copier", line 5, in <module>
    from copier.__main__ import copier_app_run
  File "/Users/kratsg/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/__init__.py", line 6, in <module>
    from .main import *  # noqa: F401,F403
  File "/Users/kratsg/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/main.py", line 46, in <module>
    from .subproject import Subproject
  File "/Users/kratsg/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/subproject.py", line 15, in <module>
    from .template import Template
  File "/Users/kratsg/.local/pipx/venvs/copier/lib/python3.10/site-packages/copier/template.py", line 20, in <module>
    from yamlinclude import YamlIncludeConstructor
ModuleNotFoundError: No module named 'yamlinclude'

Lord Stark:~/radiativeDecays (main)$ pipx run copier copy gh:scientific-python/cookie atlas --trust
⚠️  copier is already on your PATH and installed at /Users/kratsg/.local/bin/copier. Downloading and running anyway.
Copier could not load some Jinja extensions:
No module named 'copier_templates_extensions'
Make sure to install these extensions alongside Copier itself.
See the docs at https://copier.readthedocs.io/en/latest/configuring/#jinja_extensions
```

What works for me is

```
$ pipx inject copier 'pyyaml-include<2' copier-templates-extensions
  injected package pyyaml-include into venv copier
done! ✨ 🌟 ✨
  injected package copier-templates-extensions into venv copier
done! ✨ 🌟 ✨
```

so I guess the README needs to hint that there's still a `pyyaml-include` issue with the current copier?

**Comment by henryiii** [comment]
Try `pipx reinstall copier`. copier doesn't depend on pyyaml-include anymore IIRC.

**Comment by kratsg** [comment]
> Try `pipx reinstall copier`. copier doesn't depend on pyyaml-include anymore IIRC.

This worked. Dang.
